Web/Models/ErrorViewModel.cs
using System;

namespace Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Web/Controllers/ObrasDeArteController.cs
using System.Collections.Generic;
using BD.Modelos;
using Microsoft.AspNetCore.Mvc;
using Servicio;

namespace Web.Controllers
{
    public class ObrasDeArteController : Controller
    {
        private IServicioObras _servicioObras;

        public ObrasDeArteController(IServicioObras servicioObras)
        {
            _servicioObras = servicioObras;
        }

        // GET
        public IActionResult CrearObraDeArte()
        {
            return View();
        }
        
        [HttpPost]
        public IActionResult CrearObraDeArte(ObraDeArte obra)
        {
            _servicioObras.CrearObraDeArte(obra);
            return RedirectToAction(nameof(SigloXIX));
        }
        
        public IActionResult SigloXIX()
        {
            List<ObraDeArte> obrasDelSigloXIX = _servicioObras.ObtenerObrasDelSigloXIX();
            ViewBag.Obras = obrasDelSigloXIX;
            return View();
        }
    }
}

Web/Views/ObrasDeArte/CrearObraDeArte.cshtml
@model BD.Modelos.ObraDeArte;

@{
    ViewBag.Title = "Crear Obra de Arte";
    Layout = "_Layout";
}

<h2>Crear Obra de Arte</h2>
<form asp-controller="ObrasDeArte" asp-action="CrearObraDeArte" method="POST">
    <div class="form-group">
        <label asp-for="Nombre">Nombre de la obra:</label>
        <input asp-for="Nombre" type="text" class="form-control"/>
    </div>
    <div class="form-group">
        <label asp-for="AnioCreacion">Año de Creación:</label>
        <input asp-for="AnioCreacion" type="number" class="form-control"/>
    </div>
    <button class="btn btn-success" type="submit">Grabar Nueva Obra de Arte</button>
</form>

Web/Views/ObrasDeArte/SigloXIX.cshtml
@{
    ViewBag.Title = "Obras del Siglo XIX";
    Layout = "_Layout";
}

<h2>Obras del Siglo XIX</h2>
<table class="table">
    <thead>
    <tr>
        <th>Nombre obra de arte</th>
        <th>Año creación</th>
    </tr>
    </thead>
    <tbody>
        @foreach (var obra in ViewBag.Obras)
        {
            <tr>
                <td>@obra.Nombre</td>
                <td>@obra.AnioCreacion</td>
            </tr>
        }
    </tbody>
</table>

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="ObrasDeArte" asp-action="CrearObraDeArte">Home</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="ObrasDeArte" asp-action="CrearObraDeArte">Crear Obra de Arte</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="ObrasDeArte" asp-action="SigloXIX">Obras del Siglo XIX</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>